export { default as logo } from "./logo.png";
export { default as robot } from "./robot.png";
export { default as contractImg } from "./search-engines.svg";
export { default as billingImg } from "./social-media.svg";
export { default as google } from "./google.png";
export { default as appStore } from "./app.png";
export {default as menu} from "./menu.e0613cf3.svg";
export {default as close} from "./icons8-close.svg";
export {default as percent} from "./percent-svgrepo-com.svg";
export {default as card} from "./card.af071def.png";
export {default as bill} from "./bill.fd47dad8.png";
export {default as star} from "./Star.b8bf87ea.svg";
export {default as shield} from "./Shield.6d9e87e5.svg";
export {default as send} from "./Send.454b3199.svg";
export {default as quotes} from "./quotes.a87d5e6d.svg";
export {default as airbnb} from "./airbnb-ar21.svg";
export {default as binance} from "./binance.svg";
export {default as coinbase} from "./coinbase.svg";
export {default as dropbox} from "./dropbox-ar21.svg";
export {default as richard} from "./richard.69e69111.jpeg";
export {default as hamdan} from "./hamdan.b2262d5e.jpeg";
export {default as shony} from "./shony.5e4c78b7.jpeg";
export {default as instagram} from "./instagram.a54e883a.svg";
export {default as twitter} from "./twitter.8f349e28.svg";
export {default as linkedin} from "./linkedin.3be30c66.svg";
export {default as facebook} from "./facebook.b1172216.svg";